export const LOAD_WALLET = 'LOAD_WALLET';
export const LOAD_WALLET_SUCCESS = 'LOAD_WALLET_SUCCESS';
export const LOAD_WALLET_ERROR = 'LOAD_WALLET_ERROR';
export const LOAD_FILES = 'FILES_LOAD';
export const LOAD_FILES_SUCCESS = 'FILES_LOAD_SUCCESS';
export const LOAD_FILES_ERROR = 'FILES_LOAD_ERROR';