export const SEND_DEPOSIT = 'SEND_DEPOSIT';
export const SEND_DEPOSIT_SUCCESS = 'SEND_DEPOSIT_SUCCESS';
export const SEND_DEPOSIT_ERROR = 'SEND_DEPOSIT_ERROR';
export const SEND_DEPOSIT_METAMASK = 'SEND_DEPOSIT_METAMASK';
export const SEND_DEPOSIT_METAMASK_SUCCESS = 'SEND_DEPOSIT_METAMASK_SUCCESS';
export const SEND_DEPOSIT_METAMASK_ERROR= 'SEND_DEPOSIT_METAMASK_ERROR';