export const SEND_WITHDRAW = 'SEND_WITHDRAW';
export const SEND_WITHDRAW_SUCCESS = 'SEND_WITHDRAW_SUCCESS';
export const SEND_WITHDRAW_ERROR = 'SEND_WITHDRAW_ERROR';
export const SEND_WITHDRAW_METAMASK = 'SEND_WITHDRAW_METAMASK';
export const SEND_WITHDRAW_METAMASK_SUCCESS = 'SEND_WITHDRAW_METAMASK_SUCCESS';
export const SEND_WITHDRAW_METAMASK_ERROR= 'SEND_WITHDRAW_METAMASK_ERROR';