export const WEB3_LOAD = 'WEB3_LOAD';
export const WEB3_LOAD_SUCCESS = 'WEB3_LOAD_SUCCESS';
export const WEB3_LOAD_ERROR = 'WEB3_LOAD_ERROR';
export const LOAD_FILES = 'FILES_LOAD';
export const LOAD_FILES_SUCCESS = 'FILES_LOAD_SUCCESS';
export const LOAD_FILES_ERROR = 'FILES_LOAD_ERROR';