export const SEND_DEPOSIT_ON_TOP = 'SEND_DEPOSIT_ON_TOP';
export const SEND_DEPOSIT_ON_TOP_SUCCESS = 'SEND_DEPOSIT_ON_TOP_SUCCESS';
export const SEND_DEPOSIT_ON_TOP_ERROR = 'SEND_DEPOSIT_ON_TOP_ERROR';
export const SEND_DEPOSIT_ON_TOP_METAMASK = 'SEND_DEPOSIT_ON_TOP_METAMASK';
export const SEND_DEPOSIT_ON_TOP_METAMASK_SUCCESS = 'SEND_DEPOSIT_ON_TOP_METAMASK_SUCCESS';
export const SEND_DEPOSIT_ON_TOP_METAMASK_ERROR= 'SEND_DEPOSIT_ON_TOP_METAMASK_ERROR';