export const SEND_FORCEWITHDRAW = 'SEND_FORCEWITHDRAW';
export const SEND_FORCEWITHDRAW_SUCCESS = 'SEND_FORCEWITHDRAW_SUCCESS';
export const SEND_FORCEWITHDRAW_ERROR = 'SEND_FORCEWITHDRAW_ERROR';
export const SEND_FORCEWITHDRAW_METAMASK = 'SEND_FORCEWITHDRAW_METAMASK';
export const SEND_FORCEWITHDRAW_METAMASK_SUCCESS = 'SEND_FORCEWITHDRAW_METAMASK_SUCCESS';
export const SEND_FORCEWITHDRAW_METAMASK_ERROR= 'SEND_FORCEWITHDRAW_METAMASK_ERROR';